In [1]:
import json
import pandas as pd
import numpy as np

In [2]:
x = {'taxonid':[],'code':[], 'suitability':[], 'season':[], 'majorimportance':[]}
with open('data/sp_habitats.json', 'r') as f:
    data = json.load(f)
for i in data:
    for r in i['result']:
        x['taxonid'].append(i['id'])
        x['code'].append(r['code'])
        x['suitability'].append(r['suitability'])
        x['season'].append(r['season'])
        x['majorimportance'].append(r['majorimportance'])
            
habitat = pd.DataFrame(x)

In [8]:
x = {'taxonid':[],'country':[], 'presence':[], 'origin':[], 'distribution':[]}
with open('data/sp_ctry_occur.json', 'r') as f:
    data = json.load(f)

for i in data:
    for r in i['result']:
        x['taxonid'].append(i['name'])
        x['country'].append(r['code']) #only keep country code to avoid redundancy
        x['presence'].append(r['presence'])
        x['origin'].append(r['origin'])
        x['distribution'].append(r['distribution_code'])
country_occurence = pd.DataFrame(x)
country_occurence['origin'].replace('Origin Uncertain', 'Uncertain', inplace=True)

In [9]:
country_occurence.head()

  taxonid country           presence  origin        distribution
0     166      GA             Extant  Native              Native
1     219      AF  Extinct Post-1500  Native  Regionally Extinct
2     219      AO             Extant  Native              Native
3     219      BF             Extant  Native              Native
4     219      BI  Extinct Post-1500  Native  Regionally Extinct

In [10]:
x = {'taxonid':[]}
for year in range(2000, 2021):
    x[f'y{year}'] = []
    
with open('data/sp_hist_cats.json', 'r') as f:
    data = json.load(f)

for i in data:
    change_yrs = {}
    ind = 0
    start = int(i['result'][ind]['year'])
    while start >= 2000:
        change_yrs[start] = i['result'][ind]['code']
        try:   #check for next entry
            start = int(i['result'][ind+1]['year']) 
            ind += 1
        except:
            break
    x['taxonid'].append(i['name'])
    curr_cat = i['result'][ind]['code']
    
    for year in range(2000, 2021):
        if year < start: # nan for years before a species was assessed
            x[f'y{year}'].append(None)
        else:
            if year in change_yrs:
                curr_cat = change_yrs[year]
            x[f'y{year}'].append(curr_cat)

historical = pd.DataFrame(x)
to_replace = {'E':'EN', 
              'V':'VU', 
              'K':'DD', 
              'I':'DD', 
              'NR':None, 
              'LR/nt':'NT', 
              'nt':'NT', 
              'LR/lc':'LC', 
              'LR/cd':'LC'}
historical.replace(to_replace, inplace=True)

In [11]:
x = {'taxonid': [], 'code': [], 'timing': [], 'scope':[], 'severity':[], 'score':[], 'invasive':[]}
with open('data/sp_threats.json') as f:
    data = json.load(f)

for i in data:
    result = i['result']
    if result == []:
        pass
    else:
        for r in result:
            x['taxonid'].append(i['id'])
            x['code'].append(r['code'])
            x['timing'].append(r['timing'])
            x['scope'].append(r['scope'])
            x['severity'].append(r['severity'])
            x['score'].append(r['score'])
            x['invasive'].append(r['invasive'])

threat = pd.DataFrame(x)
threat['score'].replace(['Unknown', '(Not specified)'], None, inplace=True)
threat['score'].replace('Past Impact', 'P', inplace=True)
threat['score'] = [s[-1] if s else None for s in threat['score']]

for i in threat['taxonid'].unique():
    for code in ['8.1.2', '8.2.2', '8.4.2', '8.5.2']:
        if len(threat[(threat['taxonid']==i)&(threat['code']==code)])>1:
            t = threat[(threat['taxonid']==i)&(threat['code']==code)]
            species = [i for i in t['invasive'] if i]
            inds = list(t.index)
            threat.at[inds[0], 'invasive'] = ", ".join(species)
            threat.drop(inds[1:], inplace=True)

In [12]:
x = {}
with open('data/sp_indiv.json', encoding = 'utf-8') as f:
    data = json.load(f)
cols = data[0].keys()
for c in cols:
    x[c] = []

for i in data:
    for c in cols:
        x[c].append(i[c])
        
assessment = pd.DataFrame(x)
assessment.rename({'order':'order_name', 'class':'class_name'}, axis=1, inplace=True)
assessment = assessment.where(pd.notnull(assessment), None)

In [13]:
x = {'scientific':[], 'common':[], 'primary':[], 'language':[]}
with open('data/sp_common_names.json', encoding='utf-8') as f:
    data = json.load(f)

for i in data:
    result = i['result']
    if result != []:
        for r in result:
            x['scientific'].append(i['name'])
            x['common'].append(r['taxonname'])
            x['primary'].append(r['primary'])
            x['language'].append(r['language'])
common_names = pd.DataFrame(x)

In [12]:
with open('data/allCDspecies.json') as f:
    data = json.load(f)
    
x = {'taxonid':[], 'scientific':[]}
for i in data['result']:
    x['taxonid'].append(i['taxonid'])
    x['scientific'].append(i['scientific_name'])

CDspecies = pd.DataFrame(x)

with open('data/allCFspecies.json') as f:
    data = json.load(f)
    
x = {'taxonid':[], 'scientific':[]}
for i in data['result']:
    x['taxonid'].append(i['taxonid'])
    x['scientific'].append(i['scientific_name'])

CFspecies = pd.DataFrame(x)

with open('data/allCGspecies.json') as f:
    data = json.load(f)
    
x = {'taxonid':[], 'scientific':[]}
for i in data['result']:
    x['taxonid'].append(i['taxonid'])
    x['scientific'].append(i['scientific_name'])

CGspecies = pd.DataFrame(x)

with open('data/allCMspecies.json') as f:
    data = json.load(f)
    
x = {'taxonid':[], 'scientific':[]}
for i in data['result']:
    x['taxonid'].append(i['taxonid'])
    x['scientific'].append(i['scientific_name'])
CMspecies = pd.DataFrame(x)

with open('data/allGAspecies.json') as f:
    data = json.load(f)
    
x = {'taxonid':[], 'scientific':[]}
for i in data['result']:
    x['taxonid'].append(i['taxonid'])
    x['scientific'].append(i['scientific_name'])
    
GAspecies = pd.DataFrame(x)

with open('data/allGQspecies.json') as f:
    data = json.load(f)
    
x = {'taxonid':[], 'scientific':[]}
for i in data['result']:
    x['taxonid'].append(i['taxonid'])
    x['scientific'].append(i['scientific_name'])

GQspecies = pd.DataFrame(x)

In [1]:
import psycopg2 as pg
from psycopg2 import extras

In [13]:
curs.close()
conn.close()

In [14]:

conn = pg.connect(dbname=dbname, user=user, password=password, host=host)

In [15]:
# query species only found in congo basin countries
q = '''
SELECT co.taxonid, string_agg(co.country, ', ')
FROM country_occurrence as co
WHERE co.taxonid IN (SELECT DISTINCT(co.taxonid)
FROM country_occurrence as co
WHERE co.country IN ('CD', 'GA', 'CF', 'CM', 'CG', 'GQ') 
AND co.presence != 'Extinct Post-1500'
GROUP BY co.taxonid
EXCEPT
SELECT DISTINCT(co.taxonid)
FROM country_occurrence as co
WHERE co.country NOT IN ('CD', 'GA', 'CF', 'CM', 'CG', 'GQ')
AND co.presence != 'Extinct Post-1500')
GROUP BY co.taxonid
'''
curs = conn.cursor()
curs.execute(q)
curs.fetchall()

[(166, 'GA'),
 (865, 'CD, CF, CG'),
 (2053, 'CF, CG, CM, GA, GQ'),
 (2739, 'CD'),
 (2745, 'CD'),
 (3313, 'CM'),
 (3449, 'CD, CG'),
 (4138, 'CF, CG, CM, GA, GQ'),
 (4141, 'CD, CF, CG, CM, GA, GQ'),
 (4155, 'CG, GA'),
 (4207, 'CD'),
 (4216, 'CD'),
 (4230, 'GA'),
 (4235, 'GQ'),
 (4237, 'GQ'),
 (4311, 'CD'),
 (4958, 'CM'),
 (5145, 'CG, CM, GA, GQ'),
 (5221, 'CD'),
 (5222, 'CD'),
 (5263, 'CM, GQ'),
 (5561, 'CD'),
 (5562, 'CD, CF, CG, CM, GA, GQ'),
 (5565, 'CM'),
 (5567, 'CF, CM, GA, GQ'),
 (5568, 'CD'),
 (5570, 'CD'),
 (5575, 'CM'),
 (5589, 'CD, CF'),
 (5591, 'CD'),
 (5623, 'CD'),
 (5636, 'CM'),
 (5640, 'CD'),
 (6439, 'CD'),
 (6448, 'CM'),
 (6483, 'CG'),
 (8759, 'CF, CG, CM, GA, GQ'),
 (8760, 'CD, CG, CM, GA, GQ'),
 (9470, 'CD'),
 (9480, 'CD, CM'),
 (9493, 'CD, CM, GA, GQ'),
 (9759, 'CF, CG, CM, GA, GQ'),
 (10125, 'CM, GQ'),
 (10278, 'GQ'),
 (10592, 'CD, CF, CG, CM, GA'),
 (10796, 'CD, CF, CG, CM, GQ'),
 (11054, 'CM'),
 (11055, 'CM'),
 (11202, 'CM'),
 (11280, 'CD'),
 (11285, 'CD'),
 (11288, 'CG'),
 (11486, 'CM'),
 (12349, 'CD'),
 (12354, 'CD'),
 (12355, 'CD, CF, CG, CM, GA, GQ'),
 (12383, 'CM'),
 (12754, 'CG, CM, GA, GQ'),
 (12755, 'GQ'),
 (13239, 'CG'),
 (13844, 'CD'),
 (13962, 'CF'),
 (13975, 'CF'),
 (14034, 'CM'),
 (14105, 'CG, CM, GA, GQ'),
 (14106, 'GQ'),
 (14110, 'CD'),
 (14112, 'CM'),
 (14113, 'CM'),
 (15188, 'CD, UG'),
 (15628, 'CD'),
 (15925, 'CD, GA'),
 (15932, 'CD'),
 (16042, 'CD'),
 (16531, 'CD'),
 (16905, 'CD'),
 (18113, 'CM'),
 (18118, 'CM, GQ'),
 (18119, 'CD'),
 (18164, 'CF, CG, CM'),
 (18250, 'CG'),
 (18252, 'CD'),
 (18257, 'CD'),
 (18261, 'CD'),
 (18262, 'CD'),
 (18879, 'CM'),
 (19521, 'CG'),
 (19567, 'CG, GA'),
 (19908, 'CM'),
 (19909, 'CM'),
 (19910, 'CM'),
 (19911, 'CM'),
 (20161, 'CD'),
 (20864, 'CM'),
 (20865, 'CM'),
 (20866, 'CM'),
 (21140, 'CF, CG, GA'),
 (21220, 'GQ'),
 (21221, 'CM'),
 (21222, 'CD'),
 (21888, 'CM'),
 (21889, 'CM'),
 (21890, 'CM'),
 (21891, 'CM'),
 (21892, 'CM'),
 (21893, 'CM'),
 (21894, 'CM'),
 (21895, 'CM'),
 (21896, 'CM'),
 (21897, 'CM'),
 (21898, 'CM'),
 (22207, 'CD, CG, CM, GA, GQ'),
 (23204, 'CF, CG, CM'),
 (30438, 'CM'),
 (30440, 'CM'),
 (30441, 'CM'),
 (30442, 'CM'),
 (30443, 'CM'),
 (30444, 'CM, GA'),
 (30445, 'CF, CM'),
 (30447, 'CM'),
 (32080, 'CM, GA, GQ'),
 (32081, 'CM, GA'),
 (32082, 'CG, GA, GQ'),
 (32083, 'CM, GA, GQ'),
 (32084, 'GA'),
 (32085, 'GA'),
 (32086, 'GA'),
 (32087, 'GA'),
 (32088, 'GA'),
 (32089, 'GA'),
 (32090, 'GA'),
 (32091, 'GA'),
 (32092, 'GA'),
 (32093, 'GA'),
 (32094, 'GA'),
 (32095, 'GA'),
 (32176, 'GA'),
 (32182, 'CM, GA'),
 (32183, 'GA'),
 (32184, 'CM, GA'),
 (32738, 'CD'),
 (32739, 'CD'),
 (32740, 'CD'),
 (32741, 'CD'),
 (32742, 'CD'),
 (32743, 'CD'),
 (32744, 'CD'),
 (32745, 'CD'),
 (32748, 'CD'),
 (32749, 'CD'),
 (32750, 'CD'),
 (32751, 'CD'),
 (32752, 'CD'),
 (32927, 'CG, CM, GA'),
 (33184, 'CG, CM, GA'),
 (33185, 'CM, GA'),
 (33186, 'CM, GA, GQ'),
 (33213, 'CG, CM, GA, GQ'),
 (33215, 'CG, CM, GA, GQ'),
 (33219, 'CD, CG, CM, GA, GQ'),
 (34306, 'CD'),
 (34307, 'CD'),
 (34517, 'CM'),
 (34518, 'GA'),
 (34902, 'CD'),
 (36140, 'GA'),
 (36443, 'GA, GQ'),
 (36444, 'CG, GA'),
 (36445, 'CG, GA'),
 (36477, 'CM, GA'),
 (36478, 'GA'),
 (36479, 'CM, GA'),
 (36480, 'GA'),
 (36481, 'GA'),
 (36482, 'GA'),
 (36485, 'GA'),
 (36486, 'CD'),
 (37494, 'GA'),
 (37495, 'GA'),
 (37496, 'GA'),
 (37547, 'CM'),
 (37548, 'CM, GA'),
 (37818, 'GA, GQ'),
 (37819, 'GA'),
 (39474, 'CM, GA'),
 (39475, 'CM, GQ'),
 (39476, 'CM'),
 (39477, 'CM'),
 (39500, 'CM'),
 (39501, 'CM'),
 (39504, 'CM'),
 (39505, 'CM, GQ'),
 (39507, 'CM'),
 (39509, 'CM, GA'),
 (39510, 'CM, GQ'),
 (39511, 'CM, GQ'),
 (39512, 'CM'),
 (39513, 'CM'),
 (39514, 'CM, GQ'),
 (39517, 'CM'),
 (39518, 'CM'),
 (39520, 'CM'),
 (39521, 'CM'),
 (39522, 'CM'),
 (39523, 'CM'),
 (39524, 'CM'),
 (39525, 'CG, CM, GA, GQ'),
 (39526, 'CM'),
 (39527, 'CM'),
 (39528, 'CM'),
 (39529, 'CM'),
 (39530, 'CM'),
 (39531, 'CM'),
 (39532, 'CM, GQ'),
 (39534, 'CM'),
 (39535, 'CM'),
 (39536, 'CM'),
 (39537, 'CM'),
 (39538, 'CM'),
 (39539, 'CM'),
 (39556, 'CM'),
 (39557, 'CM, GQ'),
 (39558, 'CM'),
 (39560, 'CM'),
 (39562, 'CM, GQ'),
 (39563, 'CM, GQ'),
 (39564, 'CM'),
 (39565, 'CM'),
 (39566, 'CM'),
 (39567, 'CM, GQ'),
 (39568, 'CM, GA'),
 (39570, 'CM, GQ'),
 (39571, 'CM'),
 (39573, 'CM'),
 (39574, 'CM'),
 (39575, 'CM'),
 (39576, 'CM'),
 (39577, 'CM'),
 (39578, 'CM, GQ'),
 (39579, 'CM'),
 (39581, 'CM'),
 (39582, 'CM, GQ'),
 (39583, 'CM, GQ'),
 (39584, 'CM, GA'),
 (39585, 'CM'),
 (39727, 'CM'),
 (39731, 'CM'),
 (39732, 'CM'),
 (39736, 'CM'),
 (39737, 'CM'),
 (39738, 'CM'),
 (39739, 'CM'),
 (39741, 'CM'),
 (39744, 'CM'),
 (39745, 'CM, GQ'),
 (39746, 'CM, GQ'),
 (39749, 'CM'),
 (39750, 'CM'),
 (39933, 'CM'),
 (39934, 'GQ'),
 (39935, 'CM'),
 (39937, 'CM'),
 (39941, 'CM'),
 (39995, 'CD'),
 (40001, 'GQ'),
 (40002, 'GQ'),
 (40620, 'CM, GA'),
 (40648, 'CD'),
 (41025, 'GQ'),
 (41383, 'CD, CF, CG, CM, GA'),
 (41704, 'CD, CF, CG, CM, GA, GQ'),
 (41923, 'CD'),
 (41932, 'CD'),
 (41936, 'CD'),
 (43880, 'CM'),
 (43881, 'CM'),
 (43882, 'CM'),
 (43885, 'CM'),
 (43886, 'CM, GQ'),
 (43887, 'CM'),
 (43888, 'CM'),
 (43889, 'CM'),
 (43890, 'CD, CM'),
 (44522, 'CD'),
 (44526, 'CD'),
 (44789, 'CD, CM'),
 (44792, 'CD, CM'),
 (44854, 'CM'),
 (44935, 'CF, CG'),
 (45049, 'CF, CM'),
 (45050, 'CF, CG, GA'),
 (45054, 'CM'),
 (45055, 'CM'),
 (45056, 'CM'),
 (45059, 'CD'),
 (45071, 'CM'),
 (45072, 'CF, CG, CM'),
 (45078, 'CD'),
 (45089, 'CD'),
 (45090, 'CD'),
 (45404, 'CM, GQ'),
 (45405, 'CM'),
 (45409, 'CF, CM'),
 (45411, 'CM'),
 (45414, 'CM'),
 (45415, 'CM, GQ'),
 (45416, 'CM, GQ'),
 (45418, 'CG, CM, GA'),
 (45419, 'CM, GA'),
 (45420, 'CM, GA'),
 (45421, 'CM'),
 (45422, 'CD, CM, GA'),
 (45424, 'CM, GQ'),
 (45426, 'CM, GA'),
 (45429, 'CM'),
 (45430, 'CM'),
 (45431, 'CM, GQ'),
 (45432, 'CM'),
 (45433, 'CM'),
 (45434, 'CM'),
 (45435, 'CM, GQ'),
 (45436, 'CM, GQ'),
 (45437, 'CM'),
 (45439, 'CG, CM, GQ'),
 (45440, 'CG, CM, GA'),
 (45441, 'CM'),
 (45442, 'CM'),
 (45443, 'CM'),
 (45446, 'CD, CM, GA'),
 (45447, 'CM'),
 (45448, 'CM'),
 (45450, 'CM, GA'),
 (45451, 'CM, GA'),
 (45454, 'CM'),
 (45455, 'CM'),
 (45456, 'CM'),
 (45457, 'CM, GQ'),
 (45458, 'CM, GQ'),
 (45460, 'CM, GA'),
 (45874, 'CM, GA'),
 (45875, 'CM'),
 (45876, 'CM'),
 (45878, 'CM'),
 (45883, 'CM'),
 (45884, 'CM, GA'),
 (45887, 'CM'),
 (45888, 'CM, GA'),
 (45890, 'CM'),
 (45891, 'CM'),
 (45892, 'CD, CM'),
 (45893, 'CD, CM'),
 (45897, 'GQ'),
 (45898, 'CM'),
 (45899, 'CF, CM, GQ'),
 (45900, 'CM'),
 (45901, 'CM'),
 (45902, 'CM'),
 (45903, 'CM'),
 (45904, 'CM'),
 (45905, 'CD, CM, GA'),
 (45908, 'GQ'),
 (45910, 'CM'),
 (45912, 'CM'),
 (45914, 'CM'),
 (45915, 'CM, GQ'),
 (45916, 'CM, GQ'),
 (45917, 'CM'),
 (45918, 'CM, GA'),
 (45919, 'CM'),
 (45920, 'CM'),
 (45921, 'CM'),
 (45922, 'CM'),
 (45924, 'CM, GA'),
 (46159, 'CM'),
 (46161, 'CM'),
 (46162, 'CM'),
 (46163, 'CM'),
 (46164, 'CM'),
 (46166, 'CM'),
 (46167, 'CM'),
 (46170, 'CM, GA'),
 (46173, 'CM'),
 (46175, 'CM'),
 (46179, 'CF, CM, GA'),
 (46180, 'CF, CM, GA, GQ'),
 (46183, 'CM'),
 (46184, 'CM'),
 (46185, 'CM'),
 (46186, 'CM'),
 (46187, 'CM'),
 (46188, 'CM, GA'),
 (46191, 'CM'),
 (46192, 'CM'),
 (46193, 'CM'),
 (46194, 'CM'),
 (46196, 'CM'),
 (46198, 'CM, GA'),
 (46199, 'CM, GA'),
 (46351, 'CM'),
 (46352, 'CM'),
 (46353, 'CM'),
 (46354, 'CM'),
 (46356, 'CM, GA'),
 (46357, 'CM'),
 (46359, 'CM, GQ'),
 (46360, 'CM'),
 (46363, 'CM, GQ'),
 (46364, 'CG, CM'),
 (46367, 'CM'),
 (46368, 'CM'),
 (46369, 'CM'),
 (54372, 'CD'),
 (54374, 'CD'),
 (54379, 'CD'),
 (54384, 'CD'),
 (54386, 'CD, CF, CG, CM, GA'),
 (54387, 'CD, CF, CM, GA, GQ'),
 (54390, 'CD, CG, CM'),
 (54392, 'CD'),
 (54400, 'CM, GA, GQ'),
 (54401, 'CD, CF, CM, GQ'),
 (54403, 'CD, CM, GA, GQ'),
 (54407, 'CM'),
 (54410, 'CM'),
 (54411, 'CM'),
 (54415, 'CD, CF, CG, CM, GA, GQ'),
 (54417, 'CM'),
 (54418, 'CM'),
 (54420, 'CM'),
 (54422, 'CM'),
 (54423, 'CM'),
 (54424, 'CM'),
 (54425, 'CM'),
 (54426, 'CM'),
 (54427, 'CM'),
 (54429, 'GA'),
 (54430, 'CM'),
 (54431, 'CM'),
 (54432, 'CM'),
 (54433, 'CM'),
 (54434, 'CM'),
 (54436, 'CM'),
 (54438, 'GA'),
 (54439, 'CM'),
 (54440, 'CM'),
 (54630, 'CM'),
 (54688, 'CD, CG, CM, GA, GQ'),
 (54754, 'CD'),
 (54783, 'CD, CF, CG, CM, GA, GQ'),
 (54794, 'CM'),
 (54813, 'CD'),
 (54836, 'CD, CF, CM, GA'),
 (54893, 'CM'),
 (54894, 'CM'),
 (54895, 'CM'),
 (54896, 'CM'),
 (54897, 'CM'),
 (54898, 'CM'),
 (55283, 'CD'),
 (55284, 'CD, CG, GA'),
 (56062, 'CD, CM'),
 (56066, 'CM'),
 (56068, 'CD'),
 (56069, 'CM'),
 (56076, 'CM'),
 (56082, 'CD'),
 (56087, 'CG, CM, GA'),
 (56088, 'CM'),
 (56089, 'CM, GA, GQ'),
 (56090, 'CM'),
 (56091, 'CD'),
 (56093, 'CD'),
 (56095, 'CD'),
 (56107, 'CF'),
 (56109, 'CM'),
 (56110, 'CM'),
 (56113, 'CD'),
 (56120, 'CM'),
 (56121, 'CF'),
 (56124, 'CD'),
 (56129, 'CD'),
 (56131, 'CM'),
 (56134, 'CD'),
 (56138, 'CD'),
 (56145, 'CD'),
 (56147, 'CD'),
 (56152, 'CD'),
 (56156, 'CD'),
 (56157, 'CD'),
 (56167, 'CM, GA'),
 (56172, 'CD'),
 (56177, 'CF, CG, CM, GA, GQ'),
 (56179, 'CD, CF, CG, CM, GA'),
 (56184, 'CD'),
 (56190, 'CD'),
 (56199, 'CD'),
 (56201, 'CD'),
 (56202, 'CD'),
 (56209, 'CM'),
 (56223, 'CD'),
 (56233, 'CD, CF, CM'),
 (56234, 'CD'),
 (56246, 'GQ'),
 (56254, 'CD'),
 (56262, 'CD'),
 (56272, 'CD, CG, CM, GA, GQ'),
 (56278, 'CD'),
 (56287, 'CM'),
 (56295, 'CD, CG, CM, GA, GQ'),
 (58068, 'CD'),
 (58074, 'CF, CG, CM, GA, GQ'),
 (58079, 'CM, GQ'),
 (58081, 'CM, GA, GQ'),
 (58082, 'CM, GA, GQ'),
 (58084, 'CM'),
 (58089, 'CD'),
 (58093, 'CD'),
 (58094, 'CD'),
 (58101, 'CD'),
 (58102, 'CF, CG, CM, GA, GQ'),
 (58104, 'CD'),
 (58105, 'CD'),
 (58108, 'CF'),
 (58111, 'CD'),
 (58113, 'CD'),
 (58117, 'CG, CM'),
 (58125, 'CM'),
 (58127, 'CF'),
 (58131, 'CD'),
 (58136, 'CF'),
 (58139, 'CD'),
 (58141, 'CF'),
 (58152, 'CM, GQ'),
 (58155, 'CD'),
 (58156, 'CD, CG'),
 (58157, 'GA'),
 (58168, 'CM'),
 (58169, 'CF, CM, GA'),
 (58171, 'CF, CG, CM'),
 (58176, 'CM'),
 (58183, 'CD'),
 (58193, 'CD, CG, CM, GA, GQ'),
 (58198, 'CD, CF, CG, CM, GA, GQ'),
 (58199, 'CM'),
 (58231, 'CD, CF, CG, CM, GA'),
 (58233, 'CM, GA, GQ'),
 (58505, 'CD'),
 (58518, 'CD, CF, CG, CM, GA'),
 (58525, 'CD, CF, CM'),
 (59564, 'CM'),
 (59567, 'CM'),
 (59648, 'CM'),
 (59649, 'CM'),
 (59650, 'CM'),
 (59660, 'CM, GA, GQ'),
 (59695, 'CD'),
 (59705, 'CD, CM'),
 (59776, 'GA, GQ'),
 (59777, 'CD'),
 (59850, 'CD'),
 (59973, 'CD'),
 (60045, 'CD'),
 (60548, 'CD'),
 (60575, 'CD'),
 (60585, 'CD'),
 (60589, 'CD'),
 (60598, 'CD'),
 (60601, 'CD'),
 (60615, 'CD'),
 (60642, 'CD'),
 (60643, 'CD'),
 (60674, 'CD'),
 (60698, 'CD'),
 (60801, 'CD'),
 (61745, 'CM'),
 (61761, 'GA'),
 (61762, 'CM'),
 (61796, 'CM'),
 (61797, 'CM'),
 (61799, 'GA'),
 (62481, 'CG, CM, GA, GQ'),
 (134012, 'CF'),
 (134088, 'CM, GA'),
 (134102, 'CD'),
 (134160, 'CD'),
 (134200, 'CD'),
 (134247, 'CD'),
 (134250, 'CD, CF, CM, GA'),
 (134251, 'CD'),
 (134252, 'CD'),
 (134276, 'CD'),
 (134337, 'CD'),
 (134408, 'CM'),
 (134438, 'CM'),
 (134539, 'CD'),
 (134656, 'CM'),
 (134674, 'CD'),
 (134712, 'CD'),
 (134717, 'CD, GA'),
 (134759, 'CM'),
 (134944, 'CD, CF, CG'),
 (135103, 'CD, CF, GA'),
 (135862, 'CM'),
 (135994, 'CM'),
 (136180, 'CM'),
 (136214, 'CD, CF, CG, CM, GA, GQ'),
 (136461, 'GA'),
 (136615, 'CD, CF, CG, CM, GA'),
 (136619, 'CM'),
 (136678, 'CG'),
 (136916, 'CD'),
 (136937, 'CD'),
 (136947, 'CD'),
 (158552, 'CD, CF, CG, CM, GA, GQ'),
 (158553, 'CD, CG'),
 (158554, 'CD, CF, CG, GA'),
 (158557, 'CM, GA'),
 (158560, 'GA'),
 (158563, 'GA'),
 (158565, 'GA'),
 (158566, 'CG'),
 (158568, 'CD, CM, GQ'),
 (158569, 'CD'),
 (158573, 'CM'),
 (158579, 'GA'),
 (158580, 'CD'),
 (158581, 'CG, GA'),
 (158586, 'CD'),
 (158588, 'CM, GA'),
 (158592, 'CD'),
 (158593, 'CG, CM'),
 (158596, 'CD'),
 (158599, 'CD, CG'),
 (158600, 'CD, CF'),
 (158601, 'CD, CF, CG, CM, GA, GQ'),
 (158602, 'CD, CF'),
 (158603, 'CD'),
 (158604, 'GA'),
 (158605, 'CM'),
 (158606, 'GQ'),
 (158607, 'CM, GA, GQ'),
 (159787, 'CD'),
 (159810, 'CM'),
 (159818, 'CD'),
 (160002, 'CM'),
 (160038, 'CD'),
 (160111, 'CM, GA'),
 (160129, 'CD, CG, CM, GA, GQ'),
 (160200, 'CD, CF'),
 (160244, 'CD, CM'),
 (160346, 'CD, CG, CM'),
 (160413, 'CG'),
 (160465, 'CD, CF'),
 (160472, 'CF, CM'),
 (160475, 'CG, CM'),
 (160557, 'CM'),
 (160674, 'CD'),
 (160748, 'CD'),
 (160816, 'CD, CF, CG, CM, GA, GQ'),
 (160863, 'CD'),
 (160939, 'CD, CF, CG, CM, GQ'),
 (161016, 'CD, CF, CM'),
 (161058, 'CD, CF, CG, CM, GA'),
 (161186, 'GA'),
 (161187, 'CG'),
 (161224, 'CD, CF, CM'),
 (165801, 'CG, CM, GA, GQ'),
 (167945, 'CD, CF, CG'),
 (167950, 'CD, CM'),
 (167952, 'CD, CF, CG'),
 (167953, 'CD'),
 (167955, 'CM'),
 (167957, 'CD'),
 (167960, 'CG'),
 (167963, 'CD, CF, CG, CM'),
 (167965, 'CD, GA'),
 (167966, 'CD'),
 (167967, 'CD'),
 (167968, 'CD, CG'),
 (167969, 'CM'),
 (167970, 'CD'),
 (167971, 'CM'),
 (167972, 'CM'),
 (167973, 'CM, GA'),
 (167975, 'GA, GQ'),
 (167977, 'GA'),
 (167978, 'GA'),
 (167979, 'CG'),
 (167980, 'CG, GA'),
 (167985, 'CD'),
 (167989, 'CD'),
 (167991, 'CD'),
 (167992, 'CD, CF'),
 (167994, 'CD'),
 (168018, 'CD'),
 (169193, 'CM'),
 (169197, 'CM'),
 (169198, 'CM, GQ'),
 (169200, 'CM, GA, GQ'),
 (169202, 'CM'),
 (169241, 'CM, GA'),
 (169256, 'CM'),
 (169265, 'CG, CM, GA, GQ'),
 (169404, 'CM, GQ'),
 (169405, 'GQ'),
 (169406, 'CD'),
 (169409, 'CD, CF'),
 (169411, 'GA'),
 (169412, 'CM'),
 (169415, 'GA'),
 (169419, 'CD, CF, CG, CM'),
 (169421, 'CD, CF'),
 (169422, 'CD'),
 (169425, 'GA'),
 (169427, 'CD'),
 (169428, 'CD'),
 (169429, 'CD'),
 (169431, 'CM'),
 (169432, 'GA'),
 (169433, 'GA'),
 (169434, 'CD'),
 (169436, 'CG, GA'),
 (169437, 'CD'),
 (169439, 'CM'),
 (169440, 'GA'),
 (169441, 'CD, CG'),
 (169443, 'CM, GA, GQ'),
 (169444, 'CD, CG'),
 (169448, 'CM, GA, GQ'),
 (169449, 'CG, GA'),
 (169451, 'CF'),
 (169452, 'CD'),
 (169453, 'CD, CG'),
 (169454, 'CG'),
 (169461, 'CD'),
 (169462, 'CD, CG'),
 (169465, 'CM'),
 (169467, 'CD, CM'),
 (169468, 'CM'),
 (169471, 'CM'),
 (169472, 'CD'),
 (169473, 'CD'),
 (169474, 'CD, CG'),
 (169476, 'CD'),
 (169477, 'CD'),
 (170432, 'CD'),
 (172572, 'CM'),
 (173426, 'CM, GA'),
 (173560, 'CM, GA'),
 (173784, 'CM'),
 (175535, 'CM'),
 (175544, 'CD'),
 (176236, 'GA'),
 (176238, 'CM'),
 (176244, 'CD'),
 (176245, 'CM, GA, GQ'),
 (176272, 'CD'),
 (176284, 'CD'),
 (176307, 'CD, CG, GA, GQ'),
 (176314, 'GQ'),
 (176318, 'CM'),
 (176815, 'CD'),
 (178183, 'GQ'),
 (178427, 'CD'),
 (178456, 'CM'),
 (178610, 'CM'),
 (178675, 'CD, CG'),
 (178718, 'CD'),
 (180301, 'CD, CG'),
 (181544, 'CM'),
 (181545, 'CM'),
 (181546, 'CD, CG'),
 (181551, 'CM, GA'),
 (181552, 'CM, GA, GQ'),
 (181554, 'CD, CF, CG'),
 (181555, 'CD, CF'),
 (181556, 'CD'),
 (181557, 'CD, CG'),
 (181559, 'GA'),
 (181560, 'CD'),
 (181561, 'CD, CF, CG'),
 (181563, 'CD'),
 (181564, 'CM'),
 (181565, 'CD'),
 (181566, 'CD, CG'),
 (181568, 'GA, GQ'),
 (181569, 'CD'),
 (181571, 'CD, CG'),
 (181573, 'CG, GA'),
 (181578, 'CM'),
 (181580, 'CD'),
 (181581, 'CD'),
 (181582, 'CD, CF, CG'),
 (181583, 'CM'),
 (181591, 'GA'),
 (181593, 'CD, CG, CM'),
 (181594, 'CD, CF, CG'),
 (181596, 'CD'),
 (181599, 'CD, CG'),
 (181601, 'CD, CF'),
 (181608, 'CD, CF, CG'),
 (181609, 'CD'),
 (181610, 'CD, CG'),
 (181611, 'GA'),
 (181612, 'CM'),
 (181614, 'CD, CG'),
 (181616, 'CD'),
 (181621, 'CD'),
 (181622, 'CG, CM'),
 (181623, 'GA'),
 (181625, 'CD, CG'),
 (181626, 'CD'),
 (181627, 'CD'),
 (181628, 'CD'),
 (181630, 'CD, CF, CG'),
 (181634, 'CM'),
 (181635, 'CD'),
 (181644, 'GA'),
 (181645, 'GA'),
 (181650, 'CD'),
 (181652, 'CM, GA, GQ'),
 (181654, 'CD'),
 (181655, 'CD, CF, CG, CM, GA'),
 (181656, 'CD, CG'),
 (181660, 'CG'),
 (181661, 'CD'),
 (181667, 'CD'),
 (181668, 'CD'),
 (181671, 'CD'),
 (181672, 'CD, CG, CM, GA'),
 (181673, 'CM'),
 (181674, 'CD, CF, CG'),
 (181676, 'CD'),
 (181679, 'CM'),
 (181680, 'CD, CF, CG'),
 (181686, 'CD'),
 (181689, 'CD'),
 (181692, 'CD, CF, CG'),
 (181694, 'CD, CG'),
 (181695, 'CD, CF, CG, GA'),
 (181698, 'CD, CF, CG'),
 (181701, 'CG, GA'),
 (181703, 'CM, GA'),
 (181704, 'CM, GA'),
 (181706, 'GA'),
 (181707, 'CD, CM'),
 (181708, 'CD, CF, CG, CM'),
 (181709, 'CM'),
 (181712, 'CD, CF'),
 (181714, 'CD, CF, CG, CM'),
 (181718, 'CM'),
 (181720, 'CD'),
 (181724, 'CD, CF, CG'),
 (181725, 'CD'),
 (181730, 'GA'),
 (181731, 'CM'),
 (181734, 'GQ'),
 (181735, 'CD'),
 (181736, 'GA'),
 (181737, 'CD, GA'),
 (181740, 'CD'),
 (181748, 'CD, CG, CM, GA'),
 (181749, 'CD, CG'),
 (181751, 'CD'),
 (181752, 'CD, CG, GA'),
 (181753, 'CD, CG'),
 (181759, 'CG, CM, GA'),
 (181760, 'CD'),
 (181765, 'CD'),
 (181768, 'CG, GA'),
 (181769, 'CF'),
 (181770, 'CD'),
 (181771, 'CD'),
 (181772, 'CD'),
 (181773, 'CD, CG'),
 (181774, 'CD'),
 (181778, 'CD, CF, CG, CM'),
 (181780, 'CD'),
 (181784, 'CG'),
 (181785, 'CD, CF, CG'),
 (181786, 'CD'),
 (181788, 'CD, CF, CG'),
 (181789, 'CD'),
 (181790, 'CG, CM, GA'),
 (181794, 'CG, CM, GA, GQ'),
 (181795, 'CD, CG'),
 (181798, 'CD'),
 (181802, 'CM, GA'),
 (181803, 'CD'),
 (181804, 'CD, CG, CM, GA'),
 (181808, 'CD, CG'),
 (181810, 'CD, CF, CG'),
 (181811, 'GA, GQ'),
 (181817, 'CD'),
 (181820, 'CM'),
 (181822, 'CD'),
 (181825, 'CM'),
 (181827, 'CD, CF'),
 (181828, 'CG'),
 (181830, 'CD'),
 (181833, 'CD'),
 (181834, 'CD'),
 (181835, 'CM'),
 (181836, 'CG'),
 (181837, 'CG, GA, GQ'),
 (181838, 'CD'),
 (181840, 'CD'),
 (181842, 'CM'),
 (181845, 'CD, CG'),
 (181849, 'CD, CF, CG, CM, GA'),
 (181850, 'CD, CF'),
 (181860, 'CM, GA'),
 (181863, 'CG, GA'),
 (181865, 'CD, CF, CG'),
 (181866, 'CD'),
 (181870, 'CD, CF, CG'),
 (181873, 'GA'),
 (181876, 'CD'),
 (181877, 'CD'),
 (181878, 'CD'),
 (181879, 'CM'),
 (181880, 'CD'),
 (181881, 'GA'),
 (181883, 'CM'),
 (181884, 'CD'),
 (181885, 'CM, GQ'),
 (181887, 'GA'),
 (181888, 'CM'),
 (181891, 'CM'),
 (181894, 'CD, CG'),
 (181901, 'CD'),
 (181902, 'CM, GA'),
 (181903, 'GA'),
 (181904, 'GA'),
 (181907, 'CD'),
 (181908, 'CD'),
 (181909, 'CD, CF'),
 (181914, 'CM'),
 (181915, 'CD, CF, CG, CM, GA'),
 (181918, 'CD, CG'),
 (181919, 'CD, CF, CG, CM'),
 (181920, 'CD, CG'),
 (181922, 'CD'),
 (181924, 'CD'),
 (181925, 'CM'),
 (181926, 'CM'),
 (181927, 'GQ'),
 (181928, 'CM'),
 (181932, 'CD, CG'),
 (181934, 'CM'),
 (181935, 'CD, CG, CM'),
 (181940, 'CD'),
 (181942, 'CM'),
 (181944, 'CD'),
 (181947, 'CD'),
 (181948, 'GA'),
 (181952, 'CG'),
 (181953, 'CD, CF, CG, CM, GA'),
 (181954, 'CM'),
 (181955, 'CD'),
 (181956, 'CD'),
 (181957, 'GA'),
 (181959, 'CD'),
 (181960, 'CM'),
 (181961, 'CG'),
 (181963, 'CD, CF, CG, CM'),
 (181964, 'GA'),
 (181966, 'CD'),
 (181967, 'GA, GQ'),
 (181970, 'GA'),
 (181971, 'CD, CF'),
 (181972, 'CD'),
 (181974, 'CD, CF'),
 (181975, 'CD'),
 (181976, 'CM, GA, GQ'),
 (181980, 'CM'),
 (181983, 'CD, CF'),
 (181985, 'CD'),
 (181987, 'CD'),
 (181989, 'CD'),
 (181990, 'CM'),
 (181991, 'GA'),
 (181994, 'GA'),
 (181997, 'CD'),
 (181998, 'CD'),
 (181999, 'CD, CF, CG, CM'),
 (182002, 'CD'),
 (182007, 'CD, CM'),
 (182008, 'CD, CF, CG'),
 (182013, 'CD, CF, CG'),
 (182014, 'GA'),
 (182017, 'CM, GQ'),
 (182018, 'GA'),
 (182019, 'CG'),
 (182020, 'CM'),
 (182024, 'CM'),
 (182027, 'CG, GA'),
 (182028, 'CD'),
 (182029, 'GA'),
 ...]

In [16]:
q = '''
SELECT assessment.class_name, history.y2012, COUNT(*) 
FROM assessment FULL OUTER JOIN history on (assessment.taxonid=history.taxonid), CDspecies
WHERE assessment.taxonid=CDspecies.taxonid
GROUP BY assessment.class_name, history.y2012
ORDER BY assessment.class_name
'''
curs = conn.cursor()
curs.execute(q)
curs.fetchall()

[('ACTINOPTERYGII', 'DD', 170),
 ('ACTINOPTERYGII', 'LC', 769),
 ('ACTINOPTERYGII', None, 601),
 ('ACTINOPTERYGII', 'CR', 1),
 ('ACTINOPTERYGII', 'EN', 16),
 ('ACTINOPTERYGII', 'NT', 11),
 ('ACTINOPTERYGII', 'VU', 54),
 ('AGARICOMYCETES', None, 3),
 ('AMPHIBIA', 'LC', 138),
 ('AMPHIBIA', 'DD', 49),
 ('AMPHIBIA', 'EN', 3),
 ('AMPHIBIA', 'NT', 2),
 ('AMPHIBIA', 'VU', 8),
 ('AMPHIBIA', None, 24),
 ('AMPHIBIA', 'CR', 1),
 ('ARACHNIDA', None, 6),
 ('AVES', 'VU', 21),
 ('AVES', 'LC', 915),
 ('AVES', 'DD', 8),
 ('AVES', 'EN', 15),
 ('AVES', None, 164),
 ('AVES', 'NT', 29),
 ('BIVALVIA', 'DD', 7),
 ('BIVALVIA', 'EN', 3),
 ('BIVALVIA', 'LC', 34),
 ('BIVALVIA', 'VU', 5),
 ('BIVALVIA', None, 6),
 ('CEPHALOPODA', None, 22),
 ('CEPHALOPODA', 'DD', 6),
 ('CEPHALOPODA', 'LC', 2),
 ('CHONDRICHTHYES', 'DD', 14),
 ('CHONDRICHTHYES', 'CR', 2),
 ('CHONDRICHTHYES', 'NT', 2),
 ('CHONDRICHTHYES', 'LC', 4),
 ('CHONDRICHTHYES', 'EN', 3),
 ('CHONDRICHTHYES', 'VU', 8),
 ('CHONDRICHTHYES', None, 5),
 ('CYCADOPSIDA', 'LC', 1),
 ('CYCADOPSIDA', 'NT', 3),
 ('CYCADOPSIDA', 'VU', 3),
 ('GASTROPODA', 'DD', 42),
 ('GASTROPODA', 'LC', 78),
 ('GASTROPODA', 'CR', 13),
 ('GASTROPODA', None, 3),
 ('GASTROPODA', 'EN', 17),
 ('GASTROPODA', 'NT', 10),
 ('GASTROPODA', 'VU', 7),
 ('GNETOPSIDA', 'NT', 1),
 ('HOLOTHUROIDEA', None, 3),
 ('INSECTA', 'VU', 4),
 ('INSECTA', 'NT', 6),
 ('INSECTA', None, 108),
 ('INSECTA', 'DD', 32),
 ('INSECTA', 'LC', 426),
 ('LILIOPSIDA', 'VU', 3),
 ('LILIOPSIDA', 'NT', 3),
 ('LILIOPSIDA', 'CR', 3),
 ('LILIOPSIDA', 'LC', 122),
 ('LILIOPSIDA', None, 305),
 ('LILIOPSIDA', 'DD', 14),
 ('LILIOPSIDA', 'EN', 3),
 ('LYCOPODIOPSIDA', None, 3),
 ('MAGNOLIOPSIDA', 'EX', 2),
 ('MAGNOLIOPSIDA', 'NT', 37),
 ('MAGNOLIOPSIDA', 'LC', 129),
 ('MAGNOLIOPSIDA', 'DD', 8),
 ('MAGNOLIOPSIDA', 'CR', 3),
 ('MAGNOLIOPSIDA', 'EN', 15),
 ('MAGNOLIOPSIDA', 'VU', 30),
 ('MAGNOLIOPSIDA', None, 919),
 ('MAGNOLIOPSIDA', 'R', 11),
 ('MALACOSTRACA', 'DD', 10),
 ('MALACOSTRACA', 'LC', 23),
 ('MALACOSTRACA', None, 25),
 ('MALACOSTRACA', 'EN', 2),
 ('MAMMALIA', 'LC', 323),
 ('MAMMALIA', 'NT', 23),
 ('MAMMALIA', 'DD', 50),
 ('MAMMALIA', 'VU', 18),
 ('MAMMALIA', 'EN', 13),
 ('MAMMALIA', None, 38),
 ('MAMMALIA', 'CR', 7),
 ('MAXILLOPODA', 'VU', 1),
 ('MAXILLOPODA', 'DD', 2),
 ('PINOPSIDA', 'LC', 2),
 ('PINOPSIDA', 'NT', 2),
 ('POLYPODIOPSIDA', 'EN', 1),
 ('POLYPODIOPSIDA', None, 34),
 ('POLYPODIOPSIDA', 'LC', 9),
 ('REPTILIA', 'DD', 12),
 ('REPTILIA', None, 23),
 ('REPTILIA', 'VU', 3),
 ('REPTILIA', 'CR', 1),
 ('REPTILIA', 'LC', 30),
 ('SARCOPTERYGII', 'LC', 5),
 ('SARCOPTERYGII', None, 1)]

In [3]:
curs = conn.cursor()
q = '''
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
'''
curs.execute(q)
tables = curs.fetchall()
tables = [i[0] for i in tables]
tables

['cdspecies',
 'cfspecies',
 'cgspecies',
 'cmspecies',
 'gaspecies',
 'gqspecies',
 'common_name',
 'assessment',
 'country_occurrence',
 'habitat',
 'threat',
 'history']

In [17]:
curs = conn.cursor()
drop_table = "DROP TABLE assessment"
curs.execute(drop_table)
conn.commit()
curs.close()

In [18]:
create_assessments = '''
CREATE TABLE assessment (
taxonid INT PRIMARY KEY,
scientific_name VARCHAR(60) UNIQUE,
kingdom VARCHAR(8),
phylum VARCHAR(13),
class_name VARCHAR(14),
order_name VARCHAR(20),
family VARCHAR(20),
genus VARCHAR(25),
main_common_name TEXT,
authority TEXT,
published_year SMALLINT,
assessment_date DATE,
category VARCHAR(5),
criteria TEXT,
population_trend VARCHAR(10),
marine_system BOOLEAN,
freshwater_system BOOLEAN,
terrestrial_system BOOLEAN,
assessor TEXT,
reviewer TEXT,
aoo_km2 TEXT,
eoo_km2 TEXT,
elevation_upper REAL,
elevation_lower REAL,
depth_upper REAL,
depth_lower REAL,
errata_flag BOOLEAN,
errata_reason TEXT,
amended_flag BOOLEAN,
amended_reason TEXT
)
'''
curs = conn.cursor()
curs.execute(create_assessments)
conn.commit()
curs.close()

In [17]:
countries = ['CD', 'CF', 'CG', 'CM', 'GA', 'GQ']
curs = conn.cursor()
for i in countries:
    create_stmt = f'''
    CREATE TABLE {i}species (
    taxonid INT PRIMARY KEY,
    scientific VARCHAR(60)
    )
    '''
    curs.execute(create_stmt)

conn.commit()
curs.close()

In [18]:
curs = conn.cursor()

insert_stmt = 'INSERT INTO CDspecies VALUES %s'
extras.execute_values(curs, insert_stmt, [tuple(i) for i in CDspecies.values])
conn.commit()

insert_stmt = 'INSERT INTO CFspecies VALUES %s'
extras.execute_values(curs, insert_stmt, [tuple(i) for i in CFspecies.values])
conn.commit()

insert_stmt = 'INSERT INTO CGspecies VALUES %s'
extras.execute_values(curs, insert_stmt, [tuple(i) for i in CGspecies.values])
conn.commit()

insert_stmt = 'INSERT INTO CMspecies VALUES %s'
extras.execute_values(curs, insert_stmt, [tuple(i) for i in CMspecies.values])
conn.commit()

insert_stmt = 'INSERT INTO GAspecies VALUES %s'
extras.execute_values(curs, insert_stmt, [tuple(i) for i in GAspecies.values])
conn.commit()

insert_stmt = 'INSERT INTO GQspecies VALUES %s'
extras.execute_values(curs, insert_stmt, [tuple(i) for i in GQspecies.values])
conn.commit()

In [19]:
#populate the assessments table
insert_stmt = f'INSERT INTO assessment ({",".join(list(assessment))}) VALUES %s'
curs = conn.cursor()
extras.execute_values(curs, insert_stmt, [tuple(i) for i in assessment.values])
conn.commit()

In [20]:
create_country_occ = """
CREATE TABLE country_occurrence (
taxonid INT REFERENCES assessment(taxonid),
country VARCHAR(2),
presence VARCHAR(17),
origin VARCHAR(12),
distribution VARCHAR(26),
PRIMARY KEY (taxonid, country)
)
"""
curs = conn.cursor()
curs.execute(create_country_occ)
conn.commit()
curs.close()

In [21]:
insert_stmt = f'INSERT INTO country_occurrence ({",".join(list(country_occurence))}) VALUES %s'
curs = conn.cursor()
extras.execute_values(curs, insert_stmt, [tuple(i) for i in country_occurence.values])
conn.commit()

In [23]:
create_habitat = """
CREATE TABLE habitat (
taxonid INT REFERENCES assessment(taxonid),
code VARCHAR(6),
suitability VARCHAR(8),
season VARCHAR(27),
majorimportance VARCHAR(3),
PRIMARY KEY (taxonid, code)
)
"""
curs = conn.cursor()
curs.execute(create_habitat)
conn.commit()
curs.close()

In [24]:
insert_stmt = f'''INSERT INTO habitat ({",".join(list(habitat))}) VALUES %s
ON CONFLICT DO NOTHING;'''
curs = conn.cursor()
extras.execute_values(curs, insert_stmt, [tuple(i) for i in habitat.values])
conn.commit()

In [25]:
create_threats = """
CREATE TABLE threat (
taxonid INT REFERENCES assessment(taxonid),
code VARCHAR(6),
timing VARCHAR(24),
scope VARCHAR(17),
severity VARCHAR(32),
score VARCHAR(1),
invasive TEXT,
PRIMARY KEY (taxonid, code)
)
"""
curs = conn.cursor()
curs.execute(create_threats)
conn.commit()
curs.close()

In [26]:
insert_stmt = f'INSERT INTO threat ({",".join(list(threat))}) VALUES %s'
curs = conn.cursor()
extras.execute_values(curs, insert_stmt, [tuple(i) for i in threat.values])
conn.commit()

In [27]:
create_common_names = '''
CREATE TABLE common_name (
scientific VARCHAR(60) REFERENCES assessment(scientific_name),
common VARCHAR(42),
is_primary BOOLEAN,
language VARCHAR(3),
PRIMARY KEY (scientific, common)
)
'''
curs = conn.cursor()
curs.execute(create_common_names)
conn.commit()
curs.close()

In [28]:
create_historical = '''
CREATE TABLE history (
id SERIAL PRIMARY KEY,
taxonid int REFERENCES assessment(taxonid),
y2000 VARCHAR(2),
y2001 VARCHAR(2),
y2002 VARCHAR(2),
y2003 VARCHAR(2),
y2004 VARCHAR(2),
y2005 VARCHAR(2),
y2006 VARCHAR(2),
y2007 VARCHAR(2),
y2008 VARCHAR(2),
y2009 VARCHAR(2),
y2010 VARCHAR(2),
y2011 VARCHAR(2),
y2012 VARCHAR(2),
y2013 VARCHAR(2),
y2014 VARCHAR(2),
y2015 VARCHAR(2),
y2016 VARCHAR(2),
y2017 VARCHAR(2),
y2018 VARCHAR(2),
y2019 VARCHAR(2),
y2020 VARCHAR(2)
)
'''
curs = conn.cursor()
curs.execute(create_historical)
conn.commit()
curs.close()

In [32]:
insert_stmt = f'INSERT INTO history ({",".join([str(i) for i in list(historical)])}) VALUES %s'
curs = conn.cursor()
extras.execute_values(curs, insert_stmt, [tuple(i) for i in historical.values])
conn.commit()